export const pattieWorldConfig = {
    zones: [
        {
            id: 'sheet-zone',
            type: 'walkable',
            selector: "[data-pattie-zone='sheet']",
            behavior: ['walk', 'idle', 'jump'],
            weights: { walk: 65, idle: 25, jump: 5, sleep: 5 },
        },
        {
            id: 'chart-zone',
            type: 'terrain',
            selector: "[data-pattie-zone='chart']",
            behavior: ['walk', 'idle', 'jump', 'climb'],
            weights: { idle: 10, jump: 55, climb: 35 },
        },
        {
            id: 'card-zone',
            type: 'platform',
            selector: "[data-pattie-zone='card']",
            behavior: ['walk', 'idle', 'jump'],
            weights: { walk: 50, idle: 30, jump: 10, sleep: 10 },
        },
        {
            id: 'blocked-zone',
            type: 'blocked',
            selector: "[data-pattie-zone='blocked']",
            behavior: [],
            weights: {},
        },
    ],
    terrainRules: {
        cellBorder: { canWalk: true, canJump: true },
        chartBar: { canClimb: true, canStand: true, selector: "[data-pattie-terrain='chart-bar']" },
        cardEdge: { canJump: true, canStand: true },
    },
    movement: {
        frameDurationMs: 320,
        stepPx: 0.58,
        climbStepPx: 0.42,
        decisionMs: 3600,
        initialIdleMs: 1500,
        sleepAfterMs: 45000,
        spriteSize: 25,
        jumpDurationMs: 980,
        jumpArcPx: 25,
        maxJumpDistancePx: 62,
        walkDurationPerPx: 460,
        runDurationPerPx: 256,
        walkFrameDurationMs: 350,
        runFrameDurationMs: 220,
        maxTerrainDeltaPx: 96,
        maxBarHeightFromFloorPx: 132,
    },
};
