DELETE FROM typing_contents;
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급은 통장을 스쳐갔다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급날만 행복한 3분', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근하다가 새벽 출근', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '오늘은 일찍 간다 (야근 확정)', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '팀장님이 아이디어 좋다고 했다 (바로 버림)', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '칼퇴하려다 야근 알림 울림', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급은 들어오자마자 나간다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급날 행복 1분', 9, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '다 했다고 했지 잘 했다고는 안 했다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '1차 최종 진짜 최종 진짜 최종_v2', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '이 회의는 메일 한 통으로 끝날 수 있었다', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '팀장님의 잠깐 볼까는 1시간짜리다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '통장은 고속도로고 월급은 하이패스다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '말은 팀장님이 하고 일은 내가 한다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '퇴근 직전에 피드백 주시는 센스', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '내 월급만 빼고 다 오르는 기적', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '사직서는 가슴속에 품고만 있는 부적이다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '이건 금방 끝나요 (3시간 후)', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '질문하면 화내고 안 물어봐도 화냄', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '택시비 벌려고 야근하는 기분', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '휴가는 업무를 미리 당겨 하는 벌칙이다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '연봉 협상이 아니라 연봉 통보다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '본인이 하신 말도 기억 못 하시면 어떡합니까', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '넵 알겠습니다 (사실 모름)', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '화면 공유할 때 개인 톡 올까 봐 식겁함', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '퇴근하려는데 아 맞다 라고 하심', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '내 노고에 비해 월급이 너무 겸손하다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"스쳐 지나가는 인연, 그 이름은 월급"', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '이직은 지옥에서 불지옥으로 가는 과정', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '시키는 대로 했더니 왜 이렇게 했냐고 함', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '본인은 칼퇴하시면서 우리한텐 수고하라심', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '다들 의견 없으시죠? (답정너의 정석)', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '칭찬은 고래를 춤추게 하고 나를 일하게 함', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '회사 근처로 이사 가면 야근만 늘어난다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '티끌 모아 태산이라는데 내 월급은 왜 티끌', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '나락도 락이다 (야근도 일이다)', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '카드값이 내 월급을 마중 나왔다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근은 자발적입니다 (강제)', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '팀장님의 좋은 생각은 내 야근이다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '네 생각은 뭔데? (정답은 정해져 있음)', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '좋은 의견 감사합니다 (반영 안 함)', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '잘했는데 한 가지만 (열 가지)', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '택시비가 월급보다 아깝다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급은 집세에게 인사만 하고 간다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '이거 언제까지예요? 어제까지요.', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '카드값이 월급을 이긴다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '퇴근하려는데 팀장님이 외투를 벗는다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '잘 모르겠으면 물어봐 (물어보면 혼남)', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '자동이체 목록이 월급보다 길다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근하면 내일 일찍 가도 돼 (못 감)', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '화상회의 음소거 풀린 줄 모르고 욕했다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근비로 치킨 시키는 게 위로다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '면접에서 워라밸 좋다고 했는데 (거짓말이었다)', 25, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '실수령액을 보고 실수인 줄 알았다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급루팡은 나였으면 좋겠다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '네 의견을 존중해 (하지만 내 의견대로 해)', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급날 하루만 부자다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '출근 5분 전 도착이 프로다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '답장 없으면 괜찮은 거겠지 (아님)', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '주식으로 월급 벌겠다는 꿈 (손실 중)', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급은 1일에만 존재한다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급 빼고 다 오른다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근은 자기계발이래 (누가 그래)', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근 중 동기 인스타가 제일 아프다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '비상금은 월급날 다음 날에 사라진다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '회사 근처 살면 야근이 편해진다 (단점)', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '통장은 놀이터가 아니다 (월급이 논다)', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '카드값 알림이 월급보다 먼저 온다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근밥 메뉴 고민이 업무보다 심각하다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급이 목적이 되면 안 된다더라 (목적 맞다)', 25, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급날 카드값 빠지면 텅 빈다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '네 커리어를 생각해봐 (야근 정당화)', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급보다 이자가 더 많다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근해서 만든 게 다음 날 폐기됐다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급에서 빠지는 것만 알면 경제학자다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급쟁이가 부업하면 투잡이고 사장이 하면 사업 확장이다', 30, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근해서 만든 자료 아무도 안 봤다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '통장에 월급이 잠깐 쉬다 간다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '13월의 월급은 전설이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근은 미래의 나에게 보내는 선물이다 (독)', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근 도중 퇴사 검색한 적 있다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근은 살이 빠지는 줄 알았다 (쪘다)', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근비보다 택시비가 더 나온다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '월급이 통장에 잠깐 들렀다 간다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '야근비가 치킨값도 안 된다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"내가 팔면 오르고, 내가 사면 떨어진다"', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '장기투자는 물렸을 때 사용하는 고급 용어다', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"존버는 승리한다 단, 상장폐지는 제외다"', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '오늘도 시장은 나만 빼고 상승했다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"악재는 선반영, 호재는 미반영, 내 계좌는 완전반영"', 28, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '내가 안 사면 3연상이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '내가 사면 거래정지다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '분할매수의 끝은 몰빵이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"-3%는 조정, -30%는 가치투자다"', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"양전은 희망, 음전은 현실"', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '프리장은 희망이고 본장은 현실이다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '경제적 자유를 꿈꾸며 경제적 스트레스를 얻는다', 25, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"수익은 찔끔, 손실은 시원하다"', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '양봉 하나에 미래를 걸고 음봉 하나에 인생을 반성한다', 29, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '“본전 오면 판다”는 영원한 약속이다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '시장은 냉정하다 내 월급보다 냉정하다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '오늘의 교훈: 역시 현금이 최고였다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '내 평단은 시장 평균보다 항상 높다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '“이번엔 다르다”는 늘 같았다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '국장은 단련이고 미장은 중독이다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '계좌는 빨간데 눈은 빨갛다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '하락장에서는 모두가 장투 투자자다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"손절은 짧게, 후회는 길게"', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '차트는 과학인데 내 매매는 미신이다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"기업 분석은 3시간, 매수는 3초"', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '늦었다고 생각할 때가 진짜 늦었다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '하나를 보고 열을 알면 무당', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '참을 인 세 번이면 호구', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '"세상은 고통으로 가득하지만, 그것을 극복하는 사람들로도 가득하다"', 35, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '인생은 한방이 아니다. 한 번에 훅 간다', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '티끌 모아 티끌', 8, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '포기하면 편하다', 8, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '안 될 놈은 뭘 해도 안 된다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '노력은 배신하지 않는다. 가끔 배신할 뿐', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '남을 웃기기 전에 내 인생이 더 웃기다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '오늘도 무사 출근 달성', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '퇴근은 멀고 시트는 많다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '참을 인 세 번이면 야근', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('humor', '티끌 모아 월급', 8, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 여기까지 온 것만으로 충분해요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '"천천히 가도, 멈추지만 않으면 괜찮아요"', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신이 버틴 하루는 누군가에겐 꿈같은 하루일 수도 있어요', 31, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '잘하고 있어서 지친 거예요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '아무 일 없는 하루도 사실은 꽤 대단한 하루예요', 26, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '너무 오래 혼자 견디지 않았으면 좋겠어요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '쉬어가는 것도 앞으로 가는 방법 중 하나예요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 훨씬 괜찮은 사람이에요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 작은 행복 하나면 충분한 날도 있어요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '늦어도 괜찮아요 당신의 속도가 있는 거니까요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '완벽하지 않아도 사랑받을 수 있어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 지쳤을 땐 잠시 기대어 가도 괜찮아요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '어제보다 조금만 괜찮으면 충분해요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '누군가는 당신 덕분에 웃고 있어요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '삶은 생각보다 당신 편일 때가 많아요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 당신도 충분히 소중해요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 친절 하나가 하루를 바꾸기도 해요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 봄은 생각보다 가까이 있을지도 몰라요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '잘 버텨준 자신에게 조금 더 다정해져도 돼요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '괜찮아지지 않는 날에도 괜찮아요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '무너지지 않은 것만으로도 이미 대단해요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '누구에게나 흐린 날은 찾아와요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 노력은 조용히 쌓이고 있어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '언젠가는 오늘을 잘 지나왔다고 말할 날이 와요', 25, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '따뜻한 말 한마디가 오래 남는 날이 있어요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '힘든 날일수록 스스로를 미워하지 않았으면 좋겠어요', 27, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 존재만으로도 의미 있는 사람이에요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지금의 고민도 결국 지나가는 계절일 거예요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '행복은 거창한 게 아니라 작은 순간들에 숨어 있어요', 28, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '"오늘 하루도 살아낸 당신, 정말 수고 많았어요"', 25, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 충분히 잘해냈어요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '잠시 쉬어가도 괜찮아요', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 속도로 걸어가면 돼요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '스스로를 너무 몰아붙이지 않았으면 좋겠어요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 웃음 하나로도 하루는 달라질 수 있어요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 버틴 것만으로도 대단해요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지친 마음에도 반드시 봄은 와요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 강한 사람이에요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 여기까지 온 자신을 칭찬해주세요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '느리게 가도 괜찮아요 끝까지 가는 게 중요하니까요', 27, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 쉬어야 다시 걸을 수 있어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '누구나 흔들리며 살아가요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 힘들었다면 내일은 조금 나아질 거예요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 하루는 충분히 의미 있었어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '괜찮지 않은 날도 살아내면 되는 거예요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '혼자라고 느껴지는 날에도 당신은 소중해요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 위로 하나가 큰 힘이 되기도 해요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 눈물도 언젠가는 추억이 될 거예요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 누군가에게 꼭 필요한 사람이에요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '가끔은 아무것도 안 하는 시간도 필요해요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '잘하려고 애쓴 마음 자체가 아름다워요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 포기하지 않은 당신이 멋져요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '힘든 하루였다는 건 그만큼 열심히 살았다는 뜻이에요', 28, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지금처럼만 천천히 가도 괜찮아요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 마음도 충분히 쉬어야 해요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 노력은 사라지지 않아요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 이미 충분한 사람이에요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '괜찮다는 말 한마디가 필요한 날이 있어요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '잘 쉬는 것도 중요한 용기예요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 수고 많았어요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 흐린 날도 있어야 맑은 날이 더 소중해져요', 27, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '누구나 자기만의 속도로 살아가요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '완벽하지 않아도 괜찮아요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 살아낸 것만으로도 충분해요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '힘든 시간을 지나고 있다는 건 앞으로 가고 있다는 뜻이에요', 32, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 더 잘하고 있어요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 작은 행복을 놓치지 않았으면 좋겠어요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '모든 계절은 결국 지나가요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 하루가 조금이라도 따뜻했으면 좋겠어요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '스스로를 미워하지 않았으면 좋겠어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 혼자가 아니에요', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지친 날엔 잠시 기대어 가도 괜찮아요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '내일은 오늘보다 조금 더 괜찮아질 거예요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 한 걸음도 분명한 전진이에요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 미소는 생각보다 큰 힘이 돼요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 충분히 애썼어요', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '가끔은 멈춰 서도 괜찮아요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지금의 고민도 언젠가는 지나가요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 있는 그대로 소중한 사람이에요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '행복은 가까운 곳에 숨어 있어요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 오늘을 응원하고 있어요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '아무 이유 없이 지치는 날도 있어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '스스로에게 조금 더 다정해져 주세요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 상처도 언젠가는 아물어요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '괜찮지 않아도 괜찮아요', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 힘들 땐 잠시 쉬어도 돼요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 존재만으로도 충분해요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 버팀이 내일의 힘이 될 거예요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '너무 조급해하지 않아도 괜찮아요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 잘 살아가고 있어요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '모든 사람은 저마다의 아픔을 안고 살아가요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 의미 없는 시간은 아니었어요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 많은 걸 해내고 있어요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '때로는 쉬는 것도 앞으로 가는 방법이에요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '스스로를 믿어주세요', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 누군가의 위로가 되는 사람이에요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 조금 울어도 괜찮아요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '힘든 날은 잠시 기대어 가면 돼요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 무사히 지나왔네요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 내일을 응원할게요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지금 이 순간에도 충분히 잘하고 있어요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '모든 밤은 결국 아침을 만나요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 혼자 견뎌야 하는 사람이 아니에요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 휴식 하나가 큰 힘이 되기도 해요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 자신을 잃지 않아서 다행이에요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 지쳤다면 천천히 쉬어가요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 더 빛나는 사람이에요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 아픔이 영원하진 않을 거예요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 충분히 사랑받을 자격이 있어요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 살아내느라 정말 수고했어요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 계절도 반드시 다시 피어날 거예요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '잘 버티고 있다는 것만으로도 대단해요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 위로가 오래 남는 날이 있어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 노력은 헛되지 않아요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '모든 사람은 각자의 속도로 성장해요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘은 조금 쉬어도 괜찮아요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음에도 휴식이 필요해요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 괜찮은 사람이에요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 충분히 의미 있었어요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지금처럼만 가도 괜찮아요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '스스로에게 너무 엄격하지 않았으면 좋겠어요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 애쓴 자신을 안아주세요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '누구나 흔들리며 살아가요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 하루에도 분명 빛나는 순간이 있었어요', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 피곤함은 열심히 살아낸 흔적이에요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 무거운 날엔 잠시 내려놓아도 돼요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 누군가에게 큰 힘이 되는 사람이에요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '내일은 조금 더 따뜻하길 바랄게요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 잘 견뎌냈어요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '충분히 잘하고 있으니 걱정하지 마세요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 오늘도 잘 살아냈어요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 힘든 날엔 천천히 숨 쉬어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 지침도 언젠가는 지나갈 거예요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '너무 애쓰지 않아도 괜찮아요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 이미 충분히 소중해요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '쉬어가는 하루도 필요한 날이 있어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 버텨줘서 고마워요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 하루가 조금 더 편안하길 바랄게요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘은 자신에게 따뜻한 말을 건네주세요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 행복도 행복이에요', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '누구에게나 힘든 날은 찾아와요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 많은 걸 견뎌냈어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 무사해서 다행이에요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '괜찮지 않아도 괜찮다고 말해주고 싶어요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 충분히 잘해내고 있어요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '천천히 가도 결국 도착할 거예요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 아픈 날엔 잠시 쉬어가요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 존재는 그 자체로 의미 있어요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 노력도 분명 쌓이고 있어요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '잘 버티고 있다는 걸 잊지 마세요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 혼자가 아니에요', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 친절 하나가 큰 위로가 되기도 해요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 정말 수고 많았어요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 지칠 땐 잠시 기대어도 괜찮아요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 이미 충분히 괜찮은 사람이에요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '내일은 오늘보다 조금 나아질 거예요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지금의 고민도 결국 지나갈 거예요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 작은 웃음을 기억해주세요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 더 단단한 사람이에요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 살아낸 당신이 자랑스러워요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '누구나 자기만의 무게를 안고 살아가요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '너무 늦었다고 생각하지 않았으면 좋겠어요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 끝까지 버텨줘서 고마워요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 잘하고 있어요 정말로요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 쉼표 하나가 필요할 때도 있어요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 마음에도 햇살이 비칠 거예요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '힘든 날일수록 자신을 더 아껴주세요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 충분히 가치 있었어요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 누군가에게 큰 위로예요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '모든 상처는 조금씩 아물어가요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지금은 잠시 쉬어가는 시간일 뿐이에요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 충분히 사랑받을 사람입니다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 당신도 정말 괜찮아요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '너무 오래 혼자 아파하지 않았으면 좋겠어요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 하루가 따뜻하게 끝나길 바랄게요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '잘 해내지 못해도 괜찮아요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘은 그냥 버틴 것만으로 충분해요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 이미 많은 걸 이겨냈어요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 지친 날엔 자신을 안아주세요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 무너지지 않아서 대단해요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '언젠가는 웃으면서 지나온 날을 돌아보게 될 거예요', 27, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 내일엔 좋은 일이 있길 바랄게요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '너무 조급해하지 않아도 괜찮아요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 살아있어줘서 고마워요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 더 멋진 사람이에요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 슬픔도 언젠가는 옅어질 거예요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 행복 하나로도 충분한 날이 있어요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 속도로 천천히 가면 돼요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '잘 버티고 있다는 걸 꼭 기억해주세요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 당신의 편이 되어줄게요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '세상은 생각보다 당신에게 다정할지도 몰라요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 충분히 잘 보냈어요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 아플 땐 잠시 멈춰도 괜찮아요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 존재만으로도 소중해요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 고민도 언젠가는 지나갈 거예요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 잘 살아가고 있어요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '누구에게나 쉬어가는 날은 필요해요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 스스로를 지켜줘서 고마워요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 훨씬 강해요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 잘 견뎌냈어요', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '괜찮아질 날은 분명 와요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 이미 충분히 빛나고 있어요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘은 자신을 조금 더 아껴주세요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '힘든 날에도 당신은 소중해요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 노력이 언젠가 꽃필 거예요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 의미 없는 시간은 아니었어요', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 잘하고 있어요 천천히라도요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '지금의 아픔도 결국 지나갈 거예요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 살아내느라 정말 애썼어요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 하루가 조금 더 편안했으면 좋겠어요', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '너무 혼자 견디려고 하지 마세요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 충분히 괜찮은 사람입니다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 여기까지 와줘서 고마워요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 힘들 땐 잠시 쉬어가도 돼요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 봄도 곧 찾아올 거예요', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 충분히 잘했어요', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 누군가의 희망이 되는 사람이에요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '모든 밤은 결국 지나가요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 생각보다 더 따뜻한 사람이에요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 살아줘서 고마워요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 혼자가 아니라는 걸 기억해주세요', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘의 당신도 충분히 아름다워요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '마음이 흔들려도 괜찮아요', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 이미 충분히 노력하고 있어요', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘 하루도 정말 고생 많았어요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '작은 휴식 하나가 큰 힘이 될 거예요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신은 존재만으로도 의미 있어요', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '내일은 조금 더 괜찮기를 바랄게요', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '오늘도 자신을 잃지 않아줘서 고마워요', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('healing', '당신의 하루 끝에 작은 평안이 있기를 바랄게요', 25, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '나는 실패한 게 아니다 잘 되지 않는 방법 1만 가지를 발견한 것이다', 38, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 최종적인 것이 아니며 실패는 치명적인 것도 아니다', 31, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '위대한 일을 하는 유일한 방법은 자신이 하는 일을 사랑하는 것이다', 36, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '천 리 길도 한 걸음부터', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '미래를 예측하는 가장 좋은 방법은 미래를 만드는 것이다', 30, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '배우기를 멈추는 순간 우리는 늙기 시작한다', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동이 모든 성공의 기본 열쇠다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '불가능해 보이는 일도 끝내면 가능해진다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '네 자신이 되어라 다른 사람은 이미 존재한다', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행복은 습관이다 그것을 몸에 지녀라', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 준비된 사람에게 온다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 자전거를 타는 것과 같다 균형을 잡으려면 움직여야 한다', 34, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '생각하는 대로 살지 않으면 사는 대로 생각하게 된다', 28, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '어제와 똑같이 살면서 다른 미래를 기대하는 것은 어리석다', 31, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '고통 없이는 얻는 것도 없다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '당신이 할 수 있다고 믿든 할 수 없다고 믿든 믿는 대로 된다', 34, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 매일 반복한 작은 노력들의 합이다', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 용기의 크기만큼 넓어진다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '변화는 고통스럽지만 성장하지 못하는 것은 더 고통스럽다', 30, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '꿈을 이루고자 하는 용기만 있다면 모든 꿈은 이루어진다', 30, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '시간을 지배하는 자가 인생을 지배한다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행복은 목적지가 아니라 여행하는 방식이다', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 어두운 밤도 끝나고 해는 떠오른다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '넘어지는 것은 실패가 아니다 일어나지 않는 것이 실패다', 30, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '배는 항구에 있을 때 가장 안전하지만 그것이 배의 존재 이유는 아니다', 38, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '작은 기회로부터 위대한 일이 시작된다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '삶이 있는 한 희망은 있다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '교육의 목적은 지식을 채우는 것이 아니라 불을 붙이는 것이다', 33, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘 할 수 있는 일을 내일로 미루지 말라', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '노력은 배신하지 않는다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 열정을 잃지 않고 실패를 거듭할 수 있는 능력이다', 31, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '스스로를 믿어라 그러면 무엇이든 가능하다', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인내는 쓰지만 그 열매는 달다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기적은 포기하지 않는 사람에게 찾아온다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '모든 성취는 결심에서 시작된다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 준비와 기회의 만남이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실패는 성공으로 가는 과정이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동 없는 꿈은 환상일 뿐이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '지금 이 순간도 다시 오지 않는다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '사람은 꿈꾸는 대로 된다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 큰 위험은 위험 없는 삶이다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '할 수 있다고 생각하는 사람이 결국 해낸다', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 짧고 예술은 길다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '희망은 깨어 있는 사람의 꿈이다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '용기는 두려움이 없는 것이 아니라 두려움을 이기는 것이다', 31, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 스스로 만드는 것이다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생에 실패란 없다 배움만 있을 뿐', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신을 이기는 사람이 가장 강한 사람이다', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '모든 시작은 어렵다', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행복은 멀리 있지 않다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '최고의 복수는 성공이다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자유란 스스로 선택하는 것이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '한 번뿐인 인생이다', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '포기하지 않으면 반드시 길은 있다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행복은 감사하는 마음에서 시작된다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '세상은 행동하는 사람의 것이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 스스로 만드는 작품이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '작은 친절이 세상을 바꾼다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동은 모든 것을 증명한다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '배움에는 끝이 없다', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실패를 두려워하지 말고 도전하지 않는 것을 두려워하라', 29, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신의 삶을 사랑하라', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행복은 선택이다', 8, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 위대한 영광은 넘어지지 않는 데 있는 것이 아니라 넘어질 때마다 일어나는 데 있다', 48, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 자신을 발견하는 것이 아니라 자신을 만드는 것이다', 31, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '무엇을 하든 전심을 다하라', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공의 문은 늘 미는 쪽이다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '생각이 바뀌면 인생이 바뀐다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '작은 변화가 큰 차이를 만든다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '끝날 때까지는 끝난 게 아니다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '지혜는 경험의 딸이다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 도전이다', 8, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '최고의 준비는 시작하는 것이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성장은 불편함에서 시작된다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '할 수 있는 일을 하라 지금 있는 곳에서', 22, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '삶은 용기 있는 모험 아니면 아무것도 아니다', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행복한 삶은 스스로 만든다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '지금 행동하라', 7, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘이 가장 젊은 날이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '꾸준함이 재능을 이긴다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '희망은 절대 우리를 버리지 않는다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '사람은 자신이 믿는 대로 된다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '포기하지 않는 것이 가장 큰 재능이다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '노력 없는 결과는 없다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실수는 인간적이다', 9, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동하는 사람만이 변화를 만든다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '두려움 너머에 성장의 길이 있다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '삶은 오늘이라는 선물이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 작은 습관의 반복이다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '도전 없는 삶은 의미가 없다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '할 수 있을 때 최선을 다하라', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 큰 성공은 자신답게 사는 것이다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '배움은 평생의 여행이다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 늘 준비된 마음에 온다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '진실한 마음은 결국 통한다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 스스로 선택한 결과다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공보다 중요한 것은 성장이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '좋은 습관은 인생을 바꾼다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '세상은 생각보다 넓고 기회는 많다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘이라는 하루는 다시 오지 않는다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '시작이 반이다', 7, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 기다리는 것이 아니라 만드는 것이다', 23, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '천천히 가도 멈추지 않으면 된다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '작은 차이가 큰 결과를 만든다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 꾸준함이 이긴다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘 걷지 않으면 내일은 뛰어야 한다', 20, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '포기하지 않는 사람이 결국 웃는다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '습관이 인생을 만든다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '두려움 뒤에 성장이 있다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동이 생각을 이긴다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실패는 끝이 아니라 과정이다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '늦었다고 생각할 때가 시작할 때다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신감은 준비에서 나온다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 어려운 순간이 가장 많이 성장하는 순간이다', 26, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '배움에는 끝이 없다', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 선택의 연속이다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '중요한 건 속도가 아니라 방향이다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 답은 현장에 있다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '노력은 결국 흔적을 남긴다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '운도 준비된 사람 편이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '지금 하지 않으면 아무 일도 일어나지 않는다', 24, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '완벽보다 실행이 중요하다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '모든 결과에는 이유가 있다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '반복이 실력을 만든다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '생각만 하면 아무것도 변하지 않는다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '멈추지 않으면 언젠가 도착한다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 큰 적은 어제의 나다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '경험은 최고의 스승이다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '위기는 기회의 다른 이름이다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '사소한 차이가 인생을 바꾼다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신을 믿는 순간 가능성은 시작된다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동 없는 목표는 꿈에 불과하다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인내는 가장 강한 무기다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 용기 있는 사람의 몫이다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 작은 선택의 결과다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘의 선택이 미래를 만든다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '불안해도 앞으로 가야 한다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '해보기 전까지는 모른다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실패보다 후회가 더 오래 남는다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '버티는 것도 실력이다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '목표 없는 노력은 방황이다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '과정이 결과를 만든다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '한 걸음씩 가면 된다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '진짜 경쟁 상대는 자기 자신이다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 움직이는 사람에게 온다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '꾸준함은 재능을 이긴다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '작은 성공이 자신감을 만든다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 시간은 노력 편이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동은 가장 확실한 답이다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘 최선을 다하면 내일이 달라진다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '변화는 작은 결심에서 시작된다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '쉬운 길만 찾으면 멀리 못 간다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '지금의 고생이 미래의 자산이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '넘어져도 다시 일어나면 된다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 결국 마음먹기다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '도전 없는 삶은 지루하다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 반복의 힘이다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '고민보다 실행이 빠르다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 해내는 사람이 이긴다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '스스로를 이기는 사람이 강하다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '하루 차이가 인생 차이가 된다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 중요한 건 지속이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '흔들려도 앞으로 가면 된다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '노력은 결국 배신하지 않는다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 준비된 순간 찾아온다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '시작한 사람이 절반은 이긴다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '지금의 선택이 미래의 습관이 된다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 큰 실패는 포기다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '불가능은 도전 전까지의 이야기다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '작은 행동이 큰 변화를 만든다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 타이밍보다 방향이다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '포기하지 않으면 가능성은 남아 있다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '좋은 결과는 좋은 습관에서 나온다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '현실은 행동하는 사람 편이다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '계속하면 결국 는다', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신을 아는 것이 시작이다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '노력은 언젠가 연결된다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '변화는 불편함에서 시작된다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '중요한 건 다시 시작하는 힘이다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '경험은 절대 사라지지 않는다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신감은 행동에서 나온다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '불안은 성장의 신호다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '멀리 가려면 꾸준해야 한다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '반복이 차이를 만든다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '생각보다 실행이 어렵다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 행동이 답이다', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '두려움은 도전의 일부다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘의 한 걸음이 중요하다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '버틴 시간은 사라지지 않는다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실패는 다음 기회를 만든다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '스스로 한계를 만들지 마라', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '방향이 맞다면 천천히 가도 된다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 남는 건 경험이다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '시작은 언제나 어설프다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성장은 익숙함 밖에 있다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신을 속이지 마라', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '포기는 가장 쉬운 선택이다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 하루아침에 오지 않는다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 계속 배워가는 과정이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '끝까지 가는 사람이 결국 이긴다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실력은 하루아침에 만들어지지 않는다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '노력은 결국 눈에 보인다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '중요한 건 다시 도전하는 용기다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실패는 경험치를 준다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '흔들리는 건 살아 있다는 증거다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '매일 조금씩 나아가면 된다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 느린 사람도 멈춘 사람보다 빠르다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 작은 습관의 합이다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘의 경험이 내일의 자산이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 꾸준한 사람이 강하다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '완벽한 시작은 없다', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '두려워도 시작해야 한다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '작은 차이가 큰 결과를 만든다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 선택과 책임이다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '포기만 하지 않으면 기회는 남는다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실패는 방향을 알려준다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '중요한 건 끝까지 하는 힘이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘도 충분히 잘하고 있다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신을 믿는 순간 길이 열린다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 답은 행동 안에 있다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '변화는 오늘 시작된다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '도전은 성장의 시작이다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 움직이는 사람에게 온다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 강한 사람은 버티는 사람이다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '경험은 가장 값진 자산이다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '멈추지 않으면 앞으로 간다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 반복된 노력의 결과다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '용기는 작은 한 걸음에서 시작된다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '중요한 건 다시 일어나는 것이다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 결국 자신과의 싸움이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '포기하지 않으면 끝난 게 아니다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '매일의 선택이 미래를 만든다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '불안해도 가야 할 길은 있다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 성실함이 남는다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 해보는 사람의 것이다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신을 아끼는 것도 실력이다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '쉬운 길만 찾으면 성장도 없다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '끝까지 가면 보이는 것이 있다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '노력은 결국 연결된다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동이 기회를 만든다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '스스로를 믿는 힘이 중요하다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘의 실패가 내일의 실력이 된다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 큰 경쟁자는 어제의 나다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '방향을 잃지 않는 것이 중요하다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 사람은 성장한다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '두려움 속에서도 앞으로 가야 한다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성공은 포기하지 않는 사람의 것이다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '천천히라도 계속 가라', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘의 작은 변화가 미래를 바꾼다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '버티는 힘도 능력이다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 생각보다 길다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '넘어져도 괜찮다 다시 일어나면 된다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '중요한 건 속도가 아니라 지속이다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '경험은 결국 힘이 된다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '끝까지 해보는 사람이 드물다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '반복은 실력을 만든다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 행동하는 사람이 변한다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실패는 성장의 일부다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 준비된 사람 눈에 보인다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘도 한 걸음이면 충분하다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신을 믿지 않으면 아무도 믿지 않는다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 답은 꾸준함이다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '도전 없는 변화는 없다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '성장은 불편함을 견디는 힘이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '생각보다 더 강한 사람이 바로 자신이다', 21, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '계속하면 결국 도착한다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘의 노력이 내일을 만든다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '중요한 건 멈추지 않는 것이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 긴 호흡이다', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '흔들려도 방향만 잃지 마라', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 경험이 사람을 만든다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '실패를 두려워하면 아무것도 못 한다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '지금 시작해도 늦지 않았다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '스스로를 이겨야 성장한다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '좋은 결과는 좋은 과정에서 나온다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동은 가장 강력한 언어다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 남는 건 꾸준함이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신에게 솔직해져라', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘을 바꾸면 내일이 달라진다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '포기하지 않는 마음이 중요하다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '모든 시작은 어렵다', 10, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '용기는 행동에서 나온다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '작은 습관 하나가 인생을 바꾼다', 17, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 시간은 노력 편이다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '경험 없는 성공은 없다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '끝까지 해본 사람만 안다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘의 선택이 내일의 현실이다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 사람은 해내게 되어 있다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '불가능은 아직 시도하지 않은 것이다', 19, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '지금 이 순간도 기회다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '가장 중요한 건 계속 가는 힘이다', 18, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '자신만의 속도로 가면 된다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '행동하는 순간 변화가 시작된다', 16, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '결국 답은 현장에 있다', 12, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '넘어져도 다시 가면 된다', 13, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '기회는 도전 속에 숨어 있다', 15, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '노력은 결국 자신을 바꾼다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '멈추지만 않으면 된다', 11, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '인생은 끝까지 가봐야 안다', 14, 1);
INSERT INTO typing_contents (category, content, length, is_active) VALUES ('quote', '오늘의 작은 용기가 미래를 만든다', 18, 1);
