#!/usr/bin/env node

/**
 * Convert a full open-source Sudoku bank into D1 seed SQL.
 *
 * This script intentionally does not cap per difficulty level. It reads every
 * valid source puzzle and emits INSERT OR IGNORE statements.
 *
 * Usage:
 *   node scripts/generate_sudoku_bank.mjs --input ./data/sudoku_bank.csv
 *
 * Optional:
 *   node scripts/generate_sudoku_bank.mjs --input ./data/sudoku_bank.csv --output ./sudoku_bulk_seed.sql
 *
 * D1 remote execute:
 *   npx wrangler d1 execute DB --remote --file=./sudoku_bulk_seed.sql
 *
 * Supported source formats:
 *   1. CSV/TSV with headers containing puzzle+solution and optional difficulty/level.
 *   2. JSON array of objects containing puzzle+solution and optional difficulty/level.
 *   3. JSONL, one object per line.
 *   4. Plain text lines containing puzzle and solution as two 81-char digit strings.
 *
 * Expected target columns in the current Cloudflare D1 table:
 *   puzzle_id, difficulty, puzzle, solution, is_active
 *
 * The source difficulty is mapped to numeric level 1-5 and stored in the
 * existing `difficulty` column because the deployed table has no `level` column.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const DEFAULT_OUTPUT = './sudoku_bulk_seed.sql';
const ID_PREFIX = 'sudoku_bulk_';
const PUZZLE_COLUMNS = ['puzzle', 'quiz', 'question', 'givens', 'board'];
const SOLUTION_COLUMNS = ['solution', 'answer', 'solved'];
const DIFFICULTY_COLUMNS = ['level', 'difficulty', 'rating', 'rank'];

const args = parseArgs(process.argv.slice(2));

if (!args.input) {
  fail('Missing --input <path>.');
}

const inputPath = path.resolve(args.input);
const outputPath = path.resolve(args.output || DEFAULT_OUTPUT);
const raw = readFileSync(inputPath, 'utf8');
const records = parseSource(raw, inputPath);

let emitted = 0;
const lines = [
  '-- MiniGgotchi bulk Sudoku seed',
  `-- Source: ${escapeSqlComment(path.relative(process.cwd(), inputPath))}`,
  '-- Generated by scripts/generate_sudoku_bank.mjs',
  '-- D1 execute:',
  '-- npx wrangler d1 execute DB --remote --file=./sudoku_bulk_seed.sql',
];

records.forEach((record, index) => {
  const puzzle = normalizeGrid(record.puzzle);
  const solution = normalizeGrid(record.solution);

  if (!isGrid81(puzzle) || !isGrid81(solution)) {
    throw new Error(`Invalid puzzle/solution at source row ${index + 1}. Both must be 81 digits.`);
  }

  const puzzleId = `${ID_PREFIX}${String(emitted + 1).padStart(6, '0')}`;
  const level = mapDifficultyToLevel(record.difficulty);

  lines.push(
    'INSERT OR IGNORE INTO sudoku_puzzles ' +
      '(puzzle_id, difficulty, puzzle, solution, is_active) VALUES (' +
      `${sqlString(puzzleId)}, ${sqlString(String(level))}, ${sqlString(puzzle)}, ${sqlString(solution)}, 1` +
      ');',
  );
  emitted += 1;
});

lines.push('');
writeFileSync(outputPath, lines.join('\n'), 'utf8');

console.log(`Wrote ${emitted} Sudoku puzzles to ${outputPath}`);

function parseArgs(argv) {
  const parsed = {};
  for (let index = 0; index < argv.length; index += 1) {
    const current = argv[index];
    if (current === '--input' || current === '-i') {
      parsed.input = argv[index + 1];
      index += 1;
    } else if (current === '--output' || current === '-o') {
      parsed.output = argv[index + 1];
      index += 1;
    } else if (current === '--help' || current === '-h') {
      printHelp();
      process.exit(0);
    } else {
      fail(`Unknown argument: ${current}`);
    }
  }
  return parsed;
}

function parseSource(raw, inputPath) {
  const trimmed = raw.trim();
  if (!trimmed) return [];

  const ext = path.extname(inputPath).toLowerCase();
  if (ext === '.json') return parseJson(trimmed);
  if (ext === '.jsonl' || ext === '.ndjson') return parseJsonl(trimmed);

  const firstLine = trimmed.split(/\r?\n/, 1)[0];
  if (looksDelimitedWithHeader(firstLine)) return parseDelimited(trimmed);

  return parsePlainText(trimmed);
}

function parseJson(raw) {
  const data = JSON.parse(raw);
  const rows = Array.isArray(data) ? data : data.puzzles || data.rows || data.data;
  if (!Array.isArray(rows)) {
    throw new Error('JSON source must be an array or contain puzzles/rows/data array.');
  }
  return rows.map(recordFromObject);
}

function parseJsonl(raw) {
  return raw
    .split(/\r?\n/)
    .filter(Boolean)
    .map(line => recordFromObject(JSON.parse(line)));
}

function parseDelimited(raw) {
  const rows = parseCsvLike(raw);
  const headers = rows.shift().map(header => header.trim().toLowerCase());
  return rows
    .filter(row => row.some(Boolean))
    .map(row => {
      const obj = {};
      headers.forEach((header, index) => {
        obj[header] = row[index] ?? '';
      });
      return recordFromObject(obj);
    });
}

function parsePlainText(raw) {
  return raw
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(line => line && !line.startsWith('#'))
    .map((line, index) => {
      const grids = line.match(/[0-9.]{81}/g);
      if (!grids || grids.length < 2) {
        throw new Error(`Plain text row ${index + 1} must contain puzzle and solution as 81-char grids.`);
      }
      const tail = line.replace(grids[0], '').replace(grids[1], '').trim();
      return {
        puzzle: grids[0],
        solution: grids[1],
        difficulty: tail || undefined,
      };
    });
}

function recordFromObject(obj) {
  const normalized = {};
  Object.entries(obj).forEach(([key, value]) => {
    normalized[key.toLowerCase()] = value;
  });

  return {
    puzzle: pickFirst(normalized, PUZZLE_COLUMNS),
    solution: pickFirst(normalized, SOLUTION_COLUMNS),
    difficulty: pickFirst(normalized, DIFFICULTY_COLUMNS),
  };
}

function pickFirst(obj, keys) {
  for (const key of keys) {
    if (obj[key] !== undefined && obj[key] !== null && String(obj[key]).trim() !== '') {
      return String(obj[key]).trim();
    }
  }
  return undefined;
}

function normalizeGrid(value) {
  if (value === undefined || value === null) return '';
  return String(value).replace(/\./g, '0').replace(/[^0-9]/g, '');
}

function isGrid81(value) {
  return /^[0-9]{81}$/.test(value);
}

function mapDifficultyToLevel(value) {
  if (value === undefined || value === null || String(value).trim() === '') return 3;

  const raw = String(value).trim().toLowerCase();
  const numeric = Number(raw);
  if (Number.isFinite(numeric)) {
    return clamp(Math.round(numeric), 1, 5);
  }

  if (['beginner', 'very easy', 'very_easy'].includes(raw)) return 1;
  if (['easy', 'simple'].includes(raw)) return 2;
  if (['medium', 'normal', 'moderate', 'intermediate'].includes(raw)) return 3;
  if (['hard', 'difficult', 'advanced'].includes(raw)) return 4;
  if (['expert', 'evil', 'insane', 'extreme', 'diabolical'].includes(raw)) return 5;

  return 3;
}

function parseCsvLike(raw) {
  const delimiter = raw.split(/\r?\n/, 1)[0].includes('\t') ? '\t' : ',';
  const rows = [];
  let current = '';
  let row = [];
  let inQuotes = false;

  for (let index = 0; index < raw.length; index += 1) {
    const char = raw[index];
    const next = raw[index + 1];

    if (char === '"' && inQuotes && next === '"') {
      current += '"';
      index += 1;
    } else if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === delimiter && !inQuotes) {
      row.push(current);
      current = '';
    } else if ((char === '\n' || char === '\r') && !inQuotes) {
      if (char === '\r' && next === '\n') index += 1;
      row.push(current);
      rows.push(row);
      current = '';
      row = [];
    } else {
      current += char;
    }
  }

  row.push(current);
  rows.push(row);
  return rows.filter(items => items.some(item => item.trim() !== ''));
}

function looksDelimitedWithHeader(line) {
  const lower = line.toLowerCase();
  return (
    (line.includes(',') || line.includes('\t')) &&
    PUZZLE_COLUMNS.some(column => lower.includes(column)) &&
    SOLUTION_COLUMNS.some(column => lower.includes(column))
  );
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function escapeSqlComment(value) {
  return String(value).replace(/\r?\n/g, ' ');
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function printHelp() {
  console.log(`Usage: node scripts/generate_sudoku_bank.mjs --input <source-file> [--output ./sudoku_bulk_seed.sql]

Creates sudoku_bulk_seed.sql with:
  INSERT OR IGNORE INTO sudoku_puzzles (...)

D1 execute:
  npx wrangler d1 execute DB --remote --file=./sudoku_bulk_seed.sql`);
}

function fail(message) {
  console.error(message);
  printHelp();
  process.exit(1);
}
